
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zbaraszewski-n
 */
public class PokemonGUI extends javax.swing.JFrame {

    
    
    Pokemon bob = new Pokemon();
    
    protected Controller c;			// controller object
        protected DefaultListModel pokemonListModel = new DefaultListModel();
        
        
    
    
    
    
    
    /**
     * Creates new form pokemonGUI
     */
    public PokemonGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        catchButton = new javax.swing.JButton();
        wildPokemonInfoLabel = new javax.swing.JLabel();
        keepButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        wildPokemonInfoArea = new javax.swing.JTextArea();
        fleeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        yourPokemonScroll = new javax.swing.JScrollPane();
        yourPokemonList = new javax.swing.JList<>();
        yourPokemonLabel = new javax.swing.JLabel();
        yourPokemonInfoLabel = new javax.swing.JLabel();
        trainButton = new javax.swing.JButton();
        renameButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        yourPokemonInfoArea = new javax.swing.JTextArea();
        renameField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        catchButton.setText("Catch");
        catchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catchButtonActionPerformed(evt);
            }
        });

        wildPokemonInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wildPokemonInfoLabel.setText("Wild Pokemon Info");

        keepButton.setText("Keep");
        keepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keepButtonActionPerformed(evt);
            }
        });

        wildPokemonInfoArea.setColumns(20);
        wildPokemonInfoArea.setRows(5);
        jScrollPane1.setViewportView(wildPokemonInfoArea);

        fleeButton.setText("Flee");
        fleeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fleeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(catchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keepButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fleeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(wildPokemonInfoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(wildPokemonInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(catchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keepButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fleeButton)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        yourPokemonList.setModel(pokemonListModel);
        yourPokemonList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                yourPokemonListValueChanged(evt);
            }
        });
        yourPokemonScroll.setViewportView(yourPokemonList);

        yourPokemonLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yourPokemonLabel.setText("Your Pokemon");

        yourPokemonInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yourPokemonInfoLabel.setText("Your Pokemon Info");

        trainButton.setText("Train");
        trainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainButtonActionPerformed(evt);
            }
        });

        renameButton.setText("Rename");
        renameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameButtonActionPerformed(evt);
            }
        });

        yourPokemonInfoArea.setColumns(20);
        yourPokemonInfoArea.setRows(5);
        jScrollPane2.setViewportView(yourPokemonInfoArea);

        renameField.setText("Enter name");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yourPokemonScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yourPokemonLabel))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(trainButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(renameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(renameField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(77, 77, 77))
                    .addComponent(yourPokemonInfoLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yourPokemonInfoLabel)
                    .addComponent(yourPokemonLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yourPokemonScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trainButton)
                            .addComponent(renameButton)
                            .addComponent(renameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitButton))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    //generates a pokemon and displays its information in the wild pokemon info area
    private void catchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catchButtonActionPerformed
        c.createPokemon();
        wildPokemonInfoArea.setText(c.toStringPokemon());
        keepButton.setEnabled(true);
        fleeButton.setEnabled(true);
        catchButton.setEnabled(false);
    }//GEN-LAST:event_catchButtonActionPerformed

    //saves the current pokemon and adds it to the list
    private void keepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keepButtonActionPerformed
        c.keepButtonClickedInView();
        clearText();
        keepButton.setEnabled(false);
        fleeButton.setEnabled(false);
        catchButton.setEnabled(true);
    }//GEN-LAST:event_keepButtonActionPerformed

    //trains the selected pokemon
    private void trainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainButtonActionPerformed
        // TODO add your handling code here:
        yourPokemonInfoArea.setText(c.trainPokemon());
    }//GEN-LAST:event_trainButtonActionPerformed

    //removes the wild pokemon from the display
    private void fleeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fleeButtonActionPerformed
        // TODO add your handling code here:
        clearText();
        keepButton.setEnabled(false);
        fleeButton.setEnabled(false);
        catchButton.setEnabled(true);
    }//GEN-LAST:event_fleeButtonActionPerformed

    
    //sets the selected pokemons nickname to whats in the text field
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        int n = yourPokemonList.getSelectedIndex();
        String nm = renameField.getText();
        c.renamePokemon(nm);
        yourPokemonInfoArea.setText("Pokemon nickname set to " +nm +"!");
        submitButton.setEnabled(false);
        renameField.setEnabled(false);
    }//GEN-LAST:event_submitButtonActionPerformed

    //enables the text field and submit button
    private void renameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameButtonActionPerformed
        renameField.setEnabled(true);
        submitButton.setEnabled(true);
    }//GEN-LAST:event_renameButtonActionPerformed

    //this is what pokemon is selected
    private void yourPokemonListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_yourPokemonListValueChanged
        int n = yourPokemonList.getSelectedIndex();
    yourPokemonInfoArea.setText(c.getPokemon(n));
        
    }//GEN-LAST:event_yourPokemonListValueChanged

    /**
     * @param args the command line arguments
     */

protected void addController(Controller c){
		 this.c = c;
	 } // end addUI	
    
protected void clearText() {
    wildPokemonInfoArea.setText("");
}
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton catchButton;
    private javax.swing.JButton fleeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton keepButton;
    private javax.swing.JButton renameButton;
    private javax.swing.JTextField renameField;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton trainButton;
    private javax.swing.JTextArea wildPokemonInfoArea;
    private javax.swing.JLabel wildPokemonInfoLabel;
    private javax.swing.JTextArea yourPokemonInfoArea;
    private javax.swing.JLabel yourPokemonInfoLabel;
    private javax.swing.JLabel yourPokemonLabel;
    private javax.swing.JList<String> yourPokemonList;
    private javax.swing.JScrollPane yourPokemonScroll;
    // End of variables declaration//GEN-END:variables
}
